snap installer: assert injected snaps
canonical/craft-providers pull request #153
Opened 2022-09-16 21:28 UTC by mr-cal

- [X] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?

-----
### Overview
Assert signed snaps injected into a provider.

### Details
If a snap on the host is signed (not dangerous), then craft-providers will:
1. collect the assertions from the host with `snap known`
2. push the assertions to the instance
3. add the assertions in the instance with `snap ack`

If the snap is unsigned on the host, then the snap is installed dangerously in the instance.  This behavior is unchanged.

The implementation in [snapcraft_legacy](https://github.com/snapcore/snapcraft/blob/433a09262443d645acbae5204b5c9a44433f4b83/snapcraft_legacy/internal/build_providers/_snap.py) was used as a reference.

I tested this manually with snapcraft, switching between dangerous and non-dangerous snaps.  The integration tests here already test for both scenarios too (I added those tests in the [previous PR](https://github.com/canonical/craft-providers/pull/152)).

(CRAFT-1372)

2022-09-19 16:41 UTC, sergiusens commented on tests/unit/actions/test_snap_installer.py
> +        fake_process.register_subprocess(["snap", "known", fake_process.any()])
why is this needed? I admit I am not as familiar with fake_process

2022-09-19 16:42 UTC, sergiusens commented on tests/unit/actions/test_snap_installer.py
> +        fake_process.register_subprocess(["snap", "known", fake_process.any()])
Ah, I think I get it now

2022-09-19 16:44 UTC, sergiusens reviewed
Looks good, I have one question. And did you try with using an existing instance created from a released snapcraft and then moving to one using this?

2022-09-19 16:47 UTC, facundobatista requested changes
Good work!! I annotated a small detail and asked a couple of questions. Thanks!!

2022-09-19 16:47 UTC, facundobatista commented on craft_providers/actions/snap_installer.py
> +    logger.debug("Executing command on host: %s", shlex.join(command))
Just log "command". Yes, it's ugly in the sense of "a list with strings", but when a behaviour is weird and you have to debug it, having *exactly* what you executed is better.

2022-09-19 16:47 UTC, facundobatista commented on craft_providers/actions/snap_installer.py
> +            "public-key-sha3-384=BWDEoaqyr25nF5SNCvEv2v"
Where this hash comes from?

2022-09-19 16:47 UTC, facundobatista commented on craft_providers/actions/snap_installer.py
> +        assert_file = open(assert_file_path, "wb")
Where this file is closed?

2022-09-19 16:47 UTC, facundobatista commented on craft_providers/actions/snap_installer.py
> +    :yields: path to temporary assertion file
this docstring is confusing here, as this is not a "generator that yields values", but a "context manager that will set the temporary assertion file as the target"... right?

2022-09-19 19:05 UTC, mr-cal commented
> Looks good, I have one question. And did you try with using an existing instance created from a released snapcraft and then moving to one using this?

Yes, I tested this scenario too!

2022-09-20 00:33 UTC, sergiusens approved these changes

2022-09-20 17:37 UTC, facundobatista approved these changes
Awesome, thanks!

2022-09-20 17:54 UTC, merged