buildd: introduce os compatibility checks
canonical/craft-providers pull request #25
Opened 2021-04-09 23:17 UTC by cjp256

- Introduce BaseCompatibilityError.
    - Add tests for base errors.

Depends on #24

2021-04-12 20:18 UTC, sergiusens requested changes

2021-04-12 20:18 UTC, sergiusens commented on craft_providers/bases/buildd.py
> +            )
If os-release calls it NAME, I would keep that _name_ :-)

```suggestion
        os_name = os_release.get("NAME")
        if os_name != "Ubuntu":
            raise BaseCompatibilityError(
                reason=f"Exepcted OS 'Ubuntu', found {os_name!r}"
            )
```

2021-04-13 12:51 UTC, sergiusens approved these changes

2021-04-13 13:07 UTC, cmatsuoka approved these changes

2021-04-13 13:09 UTC, merged